### ISSUE TITLE
Minor Glitch. Audio in Review cards sometimes plays from beginning of article instead of context sentence.

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#87] opened 2019-05-08 08:52 UTC
In Review, playing the audio for the context sentence sometimes plays from the beginning instead (series title).

**To Reproduce**
Review
Tap play audio icon.
Hard to reproduce. Only happens sometimes.

**Expected behavior**
Should play context sentence

**Smartphone (please complete the following information):**
 Satori 1.2.0
iPad Air 3rd 2019
iOS 12.2

**Additional context**
Hard to reproduce. I was going to experiment a bit more but I mention it now just in case it might be connected with issue 85.
I have noticed:
Never happened with cloud icon only with downloaded audio triangle icon
Never on first play for displayed card. Only second or subsequent audio plays.
I can usually restore it to the context sentence position by rapidly and repeatedly jabbing the play icon. That seems to kick some sense into it. Getting practiced at that now. But play should be binary, on or off, and user should not be able to affect the play location. 
I can usually, eventually, get it to misplay from the article start. It might occur when you slightly mistap the play icon so it doesn't actually play. Then retry and the play location is wrong. 
I don't know if it is related to particular cards or article series.
I have recently started screenshoting cards that show this glitch, but no obvious cause or factor. I have mainly noticed audio saying Secret or Akiko, which I am studying, but of course older cards come up too.

Unless you think this is related to 85, or can think of a cause, I suggest you wait and I will try to investigate a bit more.

**Comment by issekinichou** [comment] 2019-05-26 13:28
See also related issue 88.

Now using Satori 1.2.1
I have made some progress hunting this bug. Still cannot reproduce it reliably on demand, but I have identified a condition that may be required for it to appear, which could be helpful. Unless you can think of a quick cause and fix, please focus on adding the review card viewing preference for now. I will continue investigating.

The bug only seems to appear in cards where the context sentence is the last one in the episode.
It does not appears with the first audio play. It only appears after the audio has reached the end of the time line.
It may be hardware related. It is common on my iPad Air 3 (2019). It is rare, but has certainly appeared on my older iPad mini 4 with same OS and Satori app.
I have only noticed it on pre-downloaded audio (triangle play icon). Not experienced it with cloud play icon, but that might reflect limited such cards. My preferences are set to middle download (favorites and bookmarks).
JE and EJ cards both show bug.
The same card that had the bug yesterday did not have it today. It's irregular. Some other factor is involved. 

I have added some cards for words in final sentences in different articles and the bug appeared in many but not all cases. Selected Miss to repeat and Hard to get it next day. A further review session found the bug for a card that was ok earlier today. Some of the same cards rated Miss tested ok on iPad mini. Some showed the bug on both.

Some cards that seem more likely to cause the bug. Final sentences.
secret 9 favorite
Secret 26
News Dino bone
sakura 16 hard

**Comment by brianrak** [comment] 2019-05-29 14:27
@issekinichou, this is very useful. The on-device audio is qualitatively different from the cloud audio, because the cloud audio is cut up into sentence-by-sentence files (for smaller, faster downloads), whereas the on-device audio plays from a marker within the already-available full-episode audio files (for instant, no-download availability). It must be that sometimes the playback head is not being moved to the end of the file properly. I will see if I can repro this using the new information you've uncovered. Thank you!

**Comment by issekinichou** [comment] 2019-05-29 14:34
Try article in browser not cards. See #88

**Comment by brianrak** [comment] 2019-05-29 21:15
I agree that this is likely not related to review cards per se. Closing this bug as a duplicate of #88.

**Closed by brianrak** 2019-05-29 21:15 UTC
