### ISSUE TITLE
Differences in app and website behavior: Review link to original article

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#36] opened 2018-08-09 10:01 UTC
**Describe the bug**
In the app, following the link to context article leads to an overlay display not the article itself. This is probably intended and seems simple and good. Only action is close X.
However, you cannot see article Discussion or see/change sidebar status, difficulty etc.

**To Reproduce**
Review, begin, any card
Tap link to original article

**Expected behavior**
Same functionality as website even if the manner is different

**Screenshots**

**Smartphone (please complete the following information):**
 - iPad mini 4
iOS 11.4.1

**Additional context**
How about adding a Navigation History page to the app? Or some other solution.
When doing a review, I sometimes follow the link to original article. In the app, the only action is close and return to review. But on website, the link opens in a new tab. I often finish the whole review and then open one or more of these article tabs to read review those articles. In the app, the article must be closed to continue the review.

**Comment by brianrak** [comment] 2018-08-12 15:46
Hello, @issekinichou. We're presenting this page modally because it is launched from the context of an in-progress review. The idea is that you can quickly view the content and return to the review.

I think your other bug (#37 ) raises a great point about missing some important controls.

We are intentionally leaving the Discussion feature out of this page for now because it contains links that don't function properly in the modal window. In the future, we hope to improve the Discussion feature so that it can be part of this screen as well.

So I'm going to call the missing Discussion issue "by design," and since your other issues are covered in #37, I'm closing this issue.

**Closed by brianrak** 2018-08-12 15:46 UTC
Labels: enhancement
