### ISSUE TITLE
Some duplicate dictionary entries

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#86] opened 2019-05-01 02:53 UTC
Some dictionary definitions seem essentially duplicated. With very minor differences, so seems like they could be merged.

I guess this is related to the content/dictionary more than the app/engine but it's a bit too technical to mention in the article discussion, so logging as a bug.

The Obon Society and Secret series both have the word shuushifu defined as completely separate dictionary entries.

So when it comes up in my keyword review list I can see the Obon society example, or I can see the Secret example, but not both together.

I wondered whether I was imagining things, but I did an export.  Found this:
e88f5480-9dc6-42d6-911c-a87f543fe7f8	JE	終止符	しゅうしふ	終止符[しゅうしふ]	終止符	終止符	full stop; period	n
2dcc350f-8d1a-4c32-b461-1880ea1db3e7	EJ	終止符	しゅうしふ	終止符[しゅうしふ]	終止符	終止符	full stop; period	n
2ba65959-0d46-4fa1-95ec-d45a3b2a28f8	JE	終止符	しゅうしふ	終止符[しゅうしふ]	終止符	終止符	full stop; period; end	n; n
52e966d0-ef31-4f5a-9ee2-fcc5bc5f4e19	EJ	終止符	しゅうしふ	終止符[しゅうしふ]	終止符	終止符	full stop; period; end	n; n

Clearly (in mind at least) two entries that could be combined into one.

I'm not sure if I'm opening up a bigger can of worms about dictionary cleanup... むすぶ seemed to be another one defined twice with one entry's definition being a pure subset of the other.

結ぶ
card IDs J/E and E/J so there are four here rather than two:
6cf10205-4b7e-4d09-b60a-ba219849fa74
fa656e69-edbc-421b-b0db-af5c58c56aba
0314e0a6-9b49-4950-b59f-df4fc04151ef
37af292a-6859-4ec4-92eb-f65b7b07f99a

Definition 1:to tie; to bind; to   link
Definition 2:to tie; to bind; to link; to unite   (with); to ally; to join hands

**Comment by brianrak** [comment] 2019-05-02 20:36
Hello, Ben. Thank you for the report!

I will take a closer look, but I think what this might be is as follows.

Cards are built around not merely a dictionary entry, but a sense within that entry. The reason for this is that many entries have lots, sometimes dozens, of individual meanings (senses). We attach dictionary entries to words in articles by the particular sense being used, and when you create a card, the sense ID is what is linked in.

Sometimes we mark two senses, a core one for the word and the one being used in the context. The context sense is the "main" one from the point of view of the card. In the case of 結ぶ, the core meaning is "tie," but a secondary sense is "unite." Therefore, two different articles might link to different ones of those senses, choosing the more appropriate one to the context. This would cause different cards to be created by design.

I think that might have happened with 終止符 too. I'll confirm and get back to you.

**Comment by bengaskin** [comment] 2019-05-02 22:39
Thanks, it's really shuushifu that I'm interested in finding out about.
Since it was specifically that word that I noticed I had to add to the
dictionary twice. I had been reading Secret and then Obon Society one after
the other so it really jumped out at me how similar even the contexts of
usage were.

結ぶ was something I was more speculative about once I had that csv data in
front of me.

**Comment by brianrak** [comment] 2019-05-29 21:24
@bengaskin, I was able to confirm that the same thing is happening for 終止符. This word has two senses:

1. Full stop; period
2. End

The first sense is the literal meaning of the word. From that sense, a secondary sense arises. It looks like when you added the word in one place, it was marked as meaning the first sense, and in another case it was marked as meaning the second (possibly with the first sense attached as a "non-context" sense). This had the result of creating multiple cards, one for each sense.

The reason we tie cards to sense and not dictionary entry is that some entries have wildly different senses. For example, if you create a card for the の that indicates possession, that's a different sort of thing from the の that nominalizes a clause, and we want to distinguish between them.

In the case of 終止符, I think we should have annotated them both simply as the first sense, since the only time it ever means "end" is as a part of the expression 終止符を打つ, "to type a period (on a particular chapter in one's life, etc)" and that expression is what causes it to mean "end."

I'm going to update the annotation on the article. What I would recommend you do is to delete the cards that include the "end" sense when you encounter them next. If you choose to re-add 終止符 from a different context later, it should aggregate the contexts together with your remaining existing cards.

Hope that helps! Thank you!

**Closed by brianrak** 2019-05-29 21:24 UTC
