### ISSUE TITLE
Specific card causes Review to get stuck in a loop

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#77] opened 2018-10-16 08:01 UTC
**Describe the bug**
This issue replaces #68. Have now found a way to reproduce bug.
A specific card 亡くなる causes the app to freeze.

**To Reproduce**
Start with a clear Review (for simplicity, not essential): 0 cards due
Obon 2 Personal Beginnings
First sentence ジーク・敬子さんは、祖父を戦争で亡くしました。
Tap 亡くしました。
Second dictionary entry. Add 亡くなる
Review. Should be 2 cards due. Tap blue button to start.
2 cards due. Tap orange button to start
Loop.
Main menu to exit. Force sync to save time.
To clear loop, open website in browser and go to Review.
It works there. 2 cards due. Note, the blue button goes straight to review card, no orange button step.
Deleting both cards clears the problem and when the app syncs, it is shows 0 due and behaves normally. 

This time I tried deleting only the JE card.
Review shows 0 cards due. Should be 1.
Popup in the article now shows blue button add to list, so it looks like it deleted.
Previously I deleted both cards and cleared to 0. That fixed the problem when the app synced.
This time, I'll see what happens in future reviews.

**Expected behavior**
Review should start like on website

**Smartphone (please complete the following information):**
 iPad mini 4, iOS 11.4.1, satori 1.0.5.

**Additional context**
I hope this is enough for you to identify some corruption in this particular card 亡くなる, and possibly in other cards, that causes the app to stumble unlike the website.
I do not intend to actively investigate this issue any further. I'll just delete that card and get back to studying.

**Comment by brianrak** [comment] 2018-11-12 17:28
Thank you, @issekinichou! I am able to reproduce this issue. This is extremely helpful.

Just to let you know, we have an update coming out this week, 1.0.7, which fixes a different issue with the review system. I have confirmed that this issue is still present in 1.0.7. We'll get this one figured out and fixed in the next update. Thank you again!

**Comment by issekinichou** [comment] 2019-01-19 16:54
Encountered the same review loop issue today.
In a second round of 4 cards. 
Browser showed they were newly added EJ, JE from a note in Sakura 36 (harder): 天の川、短冊.
Will try to narrow down cause as cards come up again.

**Comment by brianrak** [comment] 2019-03-18 18:25
@issekinichou, thank you for your help with this! This is fixed in 1.1.0 (currently in beta, will release broadly on Wednesday).

**Closed by brianrak** 2019-03-18 18:25 UTC

**Comment by issekinichou** [comment] 2019-03-19 08:30
The looping issue may be fixed but now the context is missing.
Re-added previously deleted card 天の川.
1.1.0 (1.1.2) latest. ipad mini 4. ios 12.1
![IMG_2502](https://user-images.githubusercontent.com/42171096/54590974-24020880-4a21-11e9-9557-19aa4eda6865.png)

**Comment by issekinichou** [comment] 2019-03-19 08:32
Looping issue gone, but context missing.
See comment with screenshot on GitHub.

**Comment by brianrak** [comment] 2019-03-19 15:11
Hello, @issekinichou. This is actually by design. Certain words are linked in even though they aren't actually present in the sentence. 天の川 was an example of such a word -- it didn't appear in the sentence, but we thought people might like to know it, so we had it linked as a side note. We call those "non-context-demonstrative" linked dictionary entries. Since those words can be only obliquely related to the sentence they are linked to, we don't bring along the context sentence when you add cards for them, since it doesn't really contribute much and even stands to be confusing, since the little label at the top says "You've recently seen this word in these sentences."

Previously, we had a bug where these sentences were brought in and not handled correctly by the display code. Now that that is fixed, the sentences for these words correctly do not appear.

**Comment by issekinichou** [comment] 2019-03-19 15:29
ok.
Sounds familiar. Maybe you wrote that somewhere. But it is a while since I read that article. How about a note on the card. Eg.
Intentionally lacking context
Non-context extra vocabulary
