### ISSUE TITLE
(0.912) in Disqus overlay pane, article titles do not link, nor do user names

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#45] opened 2018-08-13 13:56 UTC
**Describe the bug**
In 0.912, in the overlay pane for a user name in discussion, the article titles (eg Distraught [Koibito]) do not link to the article. Nothing happens.
Ditto tapping on another user name, eg the person being replied to. Even though blue, nothing happens.
Cannot test this in 0.913 (see issue 43)

**To Reproduce**
In 0.912, Discussion, eg Feedback, tap user name, eg Brian Rak.

**Expected behavior**
Expected links to work, as on the website

**Smartphone (please complete the following information):**
 iPad mini 4
iOS 11.4.1

**Additional context**

**Comment by brianrak** [comment] 2018-08-16 23:00
This is actually by design at the moment. The problem is that Disqus wants to link to the website, and we find that confusing behavior when you're inside an app. We're looking at a way to solve this prior to launch, possibly by moving away from Disqus. Please stand by on this.

**Comment by brianrak** [comment] 2018-08-28 21:03
This is fixed in 0.915.

**Closed by brianrak** 2018-08-28 21:03 UTC
