### ISSUE TITLE
Review not working

### ISSUE THREAD

**Issue by zantoku** [brianrak/satori-reader-mobile-beta#73] opened 2018-09-28 12:06 UTC
The review SRS is not working for me. When choosing "Review" from the menu, the overview page is shown correctly. The number of reviews shown (due, hard, all) is correct. However, when choosing either review option, after the haptic "click" feedback, the screen freezes. The button retains its "clicked" highlight color. The screen is no longer scrollable, and the button is no longer clickable. The "hamburger" menu (top left) is no longer clickable. The logo button (top right) restores the main page.

The issue is not account-specific. The problem occurs on a newly created test account.

**To Reproduce**
Choose "Review" from hamburger menu.
Tap "Review Your Cards Now".

**Expected behavior**
Review begins.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.0

**Additional context**
The Device Logs from the Preferences screen show no errors or warnings.
Brian, we corresponded over email about the issue. I hope it's ok for me to open this bug report here. If you can provide me with a version that does extended logging, I'm happy to help.

**Comment by brianrak** [comment] 2018-09-29 23:00
Hello @zantoku. Thank you for the bug report. Yes, this is perfect. 

Yesterday, a new beta build for iOS became available via TestFlight. This build has better logging around the review card system. I know you mentioned that the logs didn't show any errors. Two questions: 1) are you sure you're using 1.0.5 (confirm by looking at the bottom of the Account page)? and 2) Could you send the logs anyway after reproducing the issue? Even without a specific error message, they still might point me in the right direction.

**Comment by zantoku** [comment] 2018-10-09 08:52
Hi Brian, I can confirm the issue persists in 1.0.5. The behaviour is slightly different now: When clicking "Review Your Cards Now",  the screen is blurred and freezes in that state. Clicking the top-right area where the "home" icon is (even though it is not visible through the blur) restores the app state to the home screen.
I sent you a device log, but I'm afraid it contains nothing indicating an error.

**Comment by zantoku** [comment] 2018-11-12 09:41
@brianrak, unfortunately this issue persists in 1.0.7. Behaviour is exactly the same as before.

Let me know if I can help with debugging.

**Comment by brianrak** [comment] 2018-11-12 17:00
Thank you, @zantoku, and sorry to hear this is still happening. This is so confounding, as I can't reproduce it on my side. I would certainly welcome any help in debugging this. I'll contact you via email.

**Comment by brianrak** [comment] 2019-02-04 21:35
Fixed in 1.0.9. Huge thanks to @zantoku for all his help in tracking this down.

**Closed by brianrak** 2019-02-04 21:35 UTC
