### ISSUE TITLE
Build 1.2.0 stopped working. Crashes on launch

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#85] opened 2019-04-22 10:18 UTC
**Describe the bug**
Build 1.2.0 failed to launch this morning after overnight power off. Worked fine yesterday and recently.

**To Reproduce**
Tap to launch. Flash of colour, back to home screen. Repeat same.

**Expected behavior**
Should launch just like yesterday

**Smartphone (please complete the following information):**
 - iPad Air 3rd 2019
 - iOS 12.2

**Additional context**
This is a new iPad that I got last week. Restored from backup of iPad mini 4 running 12.2, which I still have. Satori beta worked fine for a couple of days. Can't remember if I powered down those nights, maybe not, but definitely powered down last night.
Overwrote app with purchased app store version 1.1.1. and did usually Review session.
Overwrote with Testflight beta. Same problem. Fails to launch.
Ipad mini 4 still has beta 1.2.0. No problem. Launches fine. 
Hardware issue with new iPad?
I might have powered off with Satori showing, probably in split screen mode with a dictionary.
After launch failure, double pressed home button (could see Satori open on an article) and flicked app up to quit. Relaunch. No change.
I'm back to running 1.1.1 on Air 3. Let me know if you want me to test something.

**Comment by brianrak** [comment] 2019-04-22 13:33
Hello, @issekinichou. Thank you very much for the bug report. We are working to reproduce this on our end.

**Comment by issekinichou** [comment] 2019-04-28 09:31
Good news I hope. 1.2.0 is working now.
Reinstalled from TestFlight. All normal.
Quit app (double tap home and flick up). Power off. Reboot. App working normally.

I will used it regularly and let you know if any more anomalies occur.
No idea what caused the previous problem.
All other apps fine. No other glitches.

**Comment by brianrak** [comment] 2019-04-28 15:03
Hmm. It's definitely concerning when a bug mysteriously appears and vanishes. Let's keep trying to figure out a reliable repro. Please let me know if you see this again.

**Comment by issekinichou** [comment] 2019-04-29 08:15
Crashed again this morning. One difference, useful information perhaps.
Didn't power off this time. Charged overnight. In the morning, used another app first, then Satori. Crashed, retry crashed. Reinstalled 1.1.1 for morning review. Finished review. 
Later, reinstalled 1.2.0. Normal. No problem. Will continue with 1.2.0 while it works.

**Comment by brianrak** [comment] 2019-04-29 16:16
@issekinichou, thank you for the help with this. It sounds like once it gets into a crashing state, it continues to crash every time. Further, it sounds as though a re-install is the only thing that fixes it once it is in this state. Does that sound accurate? I wonder if perhaps this is related to code we added that restores the scroll state on the most recently viewed page from the previous session. That would explain why it does not happen after a fresh install. 

When you have a moment, would you try a fresh install of 1.2.0 again and see if it goes back to a working state, then try navigating to a series page, scrolling down, then quitting the app and re-launching?

**Comment by issekinichou** [comment] 2019-04-29 16:54
1.2.0 was still working. Reinstalled purchased 1.1.1. Reinstalled 1.2.0. Opened ok.
series episode page, scroll to bottom, exit app, double tap home button and swipe up satori to quit. Reopen app. Opening screen and sync etc. 
Opened at top of episode page not bottom.
Just opening another app and then returning to satori opens at the bottom = previous scroll state.
Quit app and reopen shows same page but at the top.

Both the crashes happened after a period on non-use overnight. First power off, second charging.
The first time, reinstalling failed. This time reinstalling worked and is still working.

Finally made it crash! While typing this message on desktop mac. Tapped app icon rather than recent icon in dock. Don't know if that is relevant. Seems not.
Quit and relaunch fails.
Reinstall 1.1.1.
Reinstall 1.2.0 ok.
Quit app. App icon launches ok.
Ditto dock icon ok. All seems normal. 
So what makes it crash?
scroll down and quit. Reopens ok.
not scroll down and quit. Reopens ok.
Cannot see any cause for the crash.
Will see how it behaves in the morning.

**Comment by brianrak** [comment] 2019-05-02 20:28
I really appreciate all the diligent experimentation, @issekinichou. Please let me know if you discover reliable steps. Meanwhile, I am continuing to try to repro on my end.

**Comment by issekinichou** [comment] 2019-05-06 09:36
No crashes with 1.2.0 recently. Will certainly report any useful clues.
But some negative info might be useful.
Didn't crash after power off (once) or overnight charging (six times), so those are not inevitable causes.

The scroll position is retained when the app is reopened soon after closing, ie without a startup sync.
After closing the app at the end of an article and powering off or charging overnight, the sync in the morning opens the app at the start of the article not at the end.

**Comment by brianrak** [comment] 2019-05-08 02:30
Hello, @issekinichou. I'm just getting back to this. Would you be so kind as to send us your device logs after you get a crash? (Or, if you know you've had a crash on your current install, you can send them now.) To do this, go to Preferences, scroll to the bottom, click View Logs, then click Send Logs to Developer. Thank you very much!

**Comment by issekinichou** [comment] 2019-05-08 08:26
Not sure what you mean by current install. After it crashes, I cannot open the app to access logs. I have to reinstall earlier version 1.1.1. Did it from app store Purchased initially and then recently from TestFlight earlier builds. Overwrite 1.1.1 with 1.2.0 and use.

I had another crash later in the day of my previous post (2 days ago = May 6?) I wrote 7th in my notes, but that might mean the next day when I typed up the notes. At about 1700. No charging or power off before crash.

I have sent you the logs on my iPad and then cleared them as recommended. 
They start from 2019-04-26. I did not record crash dates, but I wrote down day of the week for the recent non crashes. Morning use is about 0530 +- a bit. UK time.

Probably Mon = April 29th
Mon night closed on dashboard, charging. Tue opened on dashboard ok. No crash.
Tue article end charging. Wed opened at article top after sync. No crash.
Wed article end power off. Thurs opened at article top after sync. No crash.
Thurs article end charging. Fri opened at article top after sync. No crash.

Mon 6th? As noted above. Crashed about 1700. No charging or power off before crash.

Wed 8th. Usual early morning study. Surprised that there was no sync and rice paddy image. Straight into article at top. Unless I blanked out. Selected review and 28 cards due. Yesterdays review completed to zero.

**Comment by brianrak** [comment] 2019-05-13 18:04
Hello @issekinichou. The logs you sent are perfect. I see crashes happening
and I think I have enough information to repro and diagnose. Thank you very
much!

**Comment by issekinichou** [comment] 2019-05-14 09:14
1.2.0 crashed again this morning 2019-05-19 after charging over night.
I reinstalled 1.1.1 and then 1.2.0 and sent the logs again and cleared logs.

**Comment by brianrak** [comment] 2019-05-29 21:14
Per our private conversation, it looks like this is fixed in the current beta. Thank you for all your help!

**Closed by brianrak** 2019-05-29 21:14 UTC
